/* eslint-disable */
/* prettier-ignore */
// oxfmt-ignore
// @ts-nocheck
// noinspection ES6UnusedImports
// Generated by vue-router. !! DO NOT MODIFY THIS FILE !!
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

import type {
  RouteRecordInfo,
  ParamValue,
  ParamValueOneOrMore,
  ParamValueZeroOrMore,
  ParamValueZeroOrOne,
} from 'vue-router'

declare module 'vue-router' {
  interface TypesConfig {
    ParamParsers:
      | never
  }
}

declare module 'vue-router/auto-routes' {
  /**
   * Route name map generated by vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<
      '/',
      '/',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/[...path]': RouteRecordInfo<
      '/[...path]',
      '/:path(.*)',
      { path: ParamValue<true> },
      { path: ParamValue<false> },
      | never
    >,
    '/about': RouteRecordInfo<
      '/about',
      '/about',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/admin': RouteRecordInfo<
      '/admin',
      '/admin',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/queue': RouteRecordInfo<
      '/queue',
      '/queue',
      Record<never, never>,
      Record<never, never>,
      | never
    >,
    '/queue.runs.[repo].[chash].[run]': RouteRecordInfo<
      '/queue.runs.[repo].[chash].[run]',
      '/queue/runs/:repo/:chash/:run',
      { repo: ParamValue<true>, chash: ParamValue<true>, run: ParamValue<true> },
      { repo: ParamValue<false>, chash: ParamValue<false>, run: ParamValue<false> },
      | never
    >,
    '/repos.[repo]': RouteRecordInfo<
      '/repos.[repo]',
      '/repos/:repo',
      { repo: ParamValue<true> },
      { repo: ParamValue<false> },
      | never
    >,
    '/repos.[repo].admin': RouteRecordInfo<
      '/repos.[repo].admin',
      '/repos/:repo/admin',
      { repo: ParamValue<true> },
      { repo: ParamValue<false> },
      | never
    >,
    '/repos.[repo].commits.[chash]': RouteRecordInfo<
      '/repos.[repo].commits.[chash]',
      '/repos/:repo/commits/:chash',
      { repo: ParamValue<true>, chash: ParamValue<true> },
      { repo: ParamValue<false>, chash: ParamValue<false> },
      | never
    >,
    '/repos.[repo].commits.[chash].runs.[run]': RouteRecordInfo<
      '/repos.[repo].commits.[chash].runs.[run]',
      '/repos/:repo/commits/:chash/runs/:run',
      { repo: ParamValue<true>, chash: ParamValue<true>, run: ParamValue<true> },
      { repo: ParamValue<false>, chash: ParamValue<false>, run: ParamValue<false> },
      | never
    >,
    '/repos.[repo].graph': RouteRecordInfo<
      '/repos.[repo].graph',
      '/repos/:repo/graph',
      { repo: ParamValue<true> },
      { repo: ParamValue<false> },
      | never
    >,
  }

  /**
   * Route file to route info map by vue-router.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * Each key is a file path relative to the project root with 2 properties:
   * - routes: union of route names of the possible routes when in this page (passed to useRoute<...>())
   * - views: names of nested views (can be passed to <RouterView name="...">)
   *
   * @internal
   */
  export interface _RouteFileInfoMap {
    'src/pages/index.vue': {
      routes:
        | '/'
      views:
        | never
    }
    'src/pages/[...path].vue': {
      routes:
        | '/[...path]'
      views:
        | never
    }
    'src/pages/about.vue': {
      routes:
        | '/about'
      views:
        | never
    }
    'src/pages/admin.vue': {
      routes:
        | '/admin'
      views:
        | never
    }
    'src/pages/queue.vue': {
      routes:
        | '/queue'
      views:
        | never
    }
    'src/pages/queue.runs.[repo].[chash].[run].vue': {
      routes:
        | '/queue.runs.[repo].[chash].[run]'
      views:
        | never
    }
    'src/pages/repos.[repo].vue': {
      routes:
        | '/repos.[repo]'
      views:
        | never
    }
    'src/pages/repos.[repo].admin.vue': {
      routes:
        | '/repos.[repo].admin'
      views:
        | never
    }
    'src/pages/repos.[repo].commits.[chash].vue': {
      routes:
        | '/repos.[repo].commits.[chash]'
      views:
        | never
    }
    'src/pages/repos.[repo].commits.[chash].runs.[run].vue': {
      routes:
        | '/repos.[repo].commits.[chash].runs.[run]'
      views:
        | never
    }
    'src/pages/repos.[repo].graph.vue': {
      routes:
        | '/repos.[repo].graph'
      views:
        | never
    }
  }

  /**
   * Get a union of possible route names in a certain route component file.
   * Used by the \`sfc-typed-router\` Volar plugin to automatically type \`useRoute()\`.
   *
   * @internal
   */
  export type _RouteNamesForFilePath<FilePath extends string> =
    _RouteFileInfoMap extends Record<FilePath, infer Info>
      ? Info['routes']
      : keyof RouteNamedMap
}

export {}
