logging:
  level: INFO
  loggers:
    org.leanlang.radar: DEBUG

dirs:
  cache: ../../radar-runner/cache/
  tmp: ../../radar-runner/tmp/

name: "testrunner"
url: "http://localhost:8080/api/"
token: "testrunnertoken"
