#!/usr/bin/env bash
set -euo pipefail

echo "##############"
echo "## radar-ui ##"
echo "##############"
pushd radar-ui
pnpm install
pnpm run build
popd

echo
echo "###########"
echo "## radar ##"
echo "###########"
pushd radar
mvn clean package
popd

echo
echo The jar is located at radar/target/radar-*.jar
