#!/usr/bin/env bash
set -euxo pipefail

pushd radar-ui
pnpm install
pnpm run build
popd

pushd radar
mvn clean package
popd

{
  echo
  echo The jar is located at radar/target/radar-*.jar
} 2>/dev/null # hide "set -x" output
